[tool.pyright]
include = ["src"]
exclude = [
    "**/__pycache__",
]
ignore = []
defineConstant = {}

reportPrivateUsage = true

pythonVersion = "3.12"
pythonPlatform = "Linux"

[tool.isort]
line_length = 88
profile = "google"
src_paths = ["src/code"]
forced_separate = ["typing"]
